version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/apps/backend"
    schedule:
      interval: "daily"
