services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - 1703:4000
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://localhost:1703
      - FRONTEND_URL=http://localhost:1702
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - 1702:3000
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://localhost:1703
      - FRONTEND_URL=http://localhost:1702
    depends_on:
      - backend
