services:
  backend:
    image: ghcr.io/csmplay/csm-mapban-backend:latest
    ports:
      - 1703:4000
    environment:
      - FRONTEND_URL=http://localhost:1702
    restart: unless-stopped

  frontend:
    image: ghcr.io/csmplay/csm-mapban-frontend:latest
    ports:
      - 1702:3000
    depends_on:
      - backend
